// packages/neo-svelte/src/components/NeoButton.svelte
<script lang="ts">
  export type Variant = 'primary' | 'accent' | 'ghost' | 'danger'
  export type Size    = 'sm' | 'md' | 'lg'
</script>

<script lang="ts">
  import { createEventDispatcher } from 'svelte'

  export let variant: Variant = 'primary'
  export let size: Size = 'md'
  export let disabled = false
  export let type: 'button' | 'submit' | 'reset' = 'button'

  const dispatch = createEventDispatcher()

  const variantClass: Record<Variant, string> = {
    primary: 'neo-btn-primary',
    accent:  'neo-btn-accent',
    ghost:   'neo-btn-ghost',
    danger:  'neo-btn-danger',
  }

  const sizeClass: Record<Size, string> = {
    sm: 'neo-btn-sm',
    md: 'neo-btn-md',
    lg: 'neo-btn-lg',
  }

  $: classes = ['neo-btn', variantClass[variant], sizeClass[size]].join(' ')
</script>

<button
  {type}
  {disabled}
  aria-disabled={disabled}
  class={classes}
  on:click
  on:focus
  on:blur
>
  <slot />
</button>

// packages/neo-vue/src/components/NeoButton.vue
<script setup lang="ts">
import { computed } from 'vue'

type Variant = 'primary' | 'accent' | 'ghost' | 'danger'
type Size = 'sm' | 'md' | 'lg'

const props = withDefaults(
  defineProps<{
    variant?: Variant
    size?: Size
    disabled?: boolean
  }>(),
  { variant: 'primary', size: 'md', disabled: false }
)

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

const variantClass: Record<Variant, string> = {
  primary: 'neo-btn-primary',
  accent:  'neo-btn-accent',
  ghost:   'neo-btn-ghost',
  danger:  'neo-btn-danger',
}

const sizeClass: Record<Size, string> = {
  sm: 'neo-btn-sm',
  md: 'neo-btn-md',
  lg: 'neo-btn-lg',
}

const classes = computed(() =>
  ['neo-btn', variantClass[props.variant], sizeClass[props.size]].join(' ')
)
</script>

<template>
  <button
    :class="classes"
    :disabled="disabled"
    :aria-disabled="disabled"
    @click="emit('click', $event)"
  >
    <slot />
  </button>
</template>
