// packages/neo-svelte/src/components/NeoProgressBar.svelte
<script lang="ts">
  export type ProgressBarVariant = 'xp' | 'hp' | 'mp'
  export let variant: ProgressBarVariant = 'xp'
  export let value: number
  export let label: string | undefined = undefined
  export let valueLabel: string | undefined = undefined
  export let striped = false

  $: pct = `${Math.min(100, Math.max(0, value))}%`
</script>

<div class="neo-{variant}-bar">
  {#if label || valueLabel}
    <div class="neo-{variant}-label">
      {#if label}<span class="neo-{variant}-label-text">{label}</span>{/if}
      {#if valueLabel}<span class="neo-{variant}-label-val">{valueLabel}</span>{/if}
    </div>
  {/if}
  <div class="neo-{variant}-track" data-striped={striped || undefined}>
    <div class="neo-{variant}-fill" style="width:{pct}" />
  </div>
</div>

// packages/neo-vue/src/components/NeoProgressBar.vue
<script setup lang="ts">
type ProgressBarVariant = 'xp' | 'hp' | 'mp'
withDefaults(defineProps<{
  variant?: ProgressBarVariant
  value: number
  label?: string
  valueLabel?: string
  striped?: boolean
}>(), { variant: 'xp', striped: false })

function clamp(v: number) { return Math.min(100, Math.max(0, v)) }
</script>

<template>
  <div :class="`neo-${variant}-bar`">
    <div v-if="label || valueLabel" :class="`neo-${variant}-label`">
      <span v-if="label" :class="`neo-${variant}-label-text`">{{ label }}</span>
      <span v-if="valueLabel" :class="`neo-${variant}-label-val`">{{ valueLabel }}</span>
    </div>
    <div :class="`neo-${variant}-track`" v-bind="striped ? { 'data-striped': '' } : {}">
      <div :class="`neo-${variant}-fill`" :style="`width:${clamp(value)}%`" />
    </div>
  </div>
</template>
