// packages/neo-svelte/src/components/NeoTag.svelte
<script lang="ts">
  export type Variant = 'brand' | 'accent' | 'ghost'

  export let variant: Variant = 'ghost'
  export let rotated = false

  const variantClass: Record<Variant, string> = {
    brand:  'neo-tag-brand',
    accent: 'neo-tag-accent',
    ghost:  'neo-tag-ghost',
  }

  $: classes = [
    'neo-tag',
    variantClass[variant],
    rotated && 'neo-tag-rotate',
  ]
    .filter(Boolean)
    .join(' ')
</script>

<span class={classes}><slot /></span>

// packages/neo-vue/src/components/NeoTag.vue
<script setup lang="ts">
import { computed } from 'vue'

type Variant = 'brand' | 'accent' | 'ghost'

const props = withDefaults(
  defineProps<{
    variant?: Variant
    rotated?: boolean
  }>(),
  { variant: 'ghost', rotated: false }
)

const variantClass: Record<Variant, string> = {
  brand:  'neo-tag-brand',
  accent: 'neo-tag-accent',
  ghost:  'neo-tag-ghost',
}

const classes = computed(() =>
  [
    'neo-tag',
    variantClass[props.variant],
    props.rotated && 'neo-tag-rotate',
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <span :class="classes"><slot /></span>
</template>
