// packages/neo-vue/src/components/NeoAlert.vue
<script setup lang="ts">
import { computed } from 'vue'

type Variant = 'success' | 'warning' | 'error' | 'info'

const props = withDefaults(
  defineProps<{
    variant?: Variant
    title?: string
  }>(),
  { variant: 'info' }
)

const variantClass: Record<Variant, string> = {
  success: 'neo-alert-success',
  warning: 'neo-alert-warning',
  error:   'neo-alert-error',
  info:    'neo-alert-info',
}

const classes = computed(() =>
  ['neo-alert', variantClass[props.variant]].join(' ')
)
</script>

<template>
  <div role="alert" :class="classes">
    <span v-if="$slots.icon" class="neo-alert__icon" aria-hidden="true">
      <slot name="icon" />
    </span>
    <p class="neo-alert__content">
      <strong v-if="title" class="neo-alert__title">{{ title }} —&nbsp;</strong>
      <slot />
    </p>
  </div>
</template>

// packages/neo-svelte/src/components/NeoAlert.svelte
<script lang="ts">
  export type Variant = 'success' | 'warning' | 'error' | 'info'

  export let variant: Variant = 'info'
  export let title = ''

  const variantClass: Record<Variant, string> = {
    success: 'neo-alert-success',
    warning: 'neo-alert-warning',
    error:   'neo-alert-error',
    info:    'neo-alert-info',
  }

  $: classes = ['neo-alert', variantClass[variant]].join(' ')
</script>

<div role="alert" class={classes}>
  {#if $$slots.icon}
    <span class="neo-alert__icon" aria-hidden="true">
      <slot name="icon" />
    </span>
  {/if}
  <p class="neo-alert__content">
    {#if title}
      <strong class="neo-alert__title">{title} —&nbsp;</strong>
    {/if}
    <slot />
  </p>
</div>
