// packages/neo-vue/src/components/NeoCard.vue
<script setup lang="ts">
import { computed } from 'vue'

type Variant = 'default' | 'brand' | 'stat' | 'filter'

const props = withDefaults(
  defineProps<{
    variant?: Variant
    pattern?: boolean
    starred?: boolean
  }>(),
  { variant: 'default', pattern: false, starred: false }
)

const variantClass: Record<Variant, string> = {
  default: 'neo-card',
  brand:   'neo-card-brand',
  stat:    'neo-stat-card',
  filter:  'neo-filter-card',
}

const classes = computed(() =>
  [
    variantClass[props.variant],
    props.pattern && 'neo-card-pattern',
    props.starred && 'neo-star',
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div :class="classes">
    <slot />
  </div>
</template>

// packages/neo-svelte/src/components/NeoCard.svelte
<script lang="ts">
  export type Variant = 'default' | 'brand' | 'stat' | 'filter'

  export let variant: Variant = 'default'
  export let pattern = false
  export let starred = false

  const variantClass: Record<Variant, string> = {
    default: 'neo-card',
    brand:   'neo-card-brand',
    stat:    'neo-stat-card',
    filter:  'neo-filter-card',
  }

  $: classes = [
    variantClass[variant],
    pattern && 'neo-card-pattern',
    starred && 'neo-star',
  ]
    .filter(Boolean)
    .join(' ')
</script>

<div class={classes}>
  <slot />
</div>
